### ISSUE TITLE
Pip install fails with gcc error compiling

### ISSUE THREAD

**Issue by loran750** [mysociety/fmsgame#3]
Hello

here is the output I get when I'm on the pip install step :

(.venv)root@myserver:/var/www/fmsgame# pip install -r requirements.txt
Downloading/unpacking psycopg2 (from -r requirements.txt (line 1))
  Running setup.py egg_info for package psycopg2

Downloading/unpacking django>=1.4 (from -r requirements.txt (line 3))
  Running setup.py egg_info for package django

```
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
```

Downloading/unpacking django-openid-auth (from -r requirements.txt (line 4))
  Running setup.py egg_info for package django-openid-auth

Downloading/unpacking python-openid (from -r requirements.txt (line 6))
  Running setup.py egg_info for package python-openid

```
warning: no files found matching 'CHANGELOG'
warning: no files found matching '*.css' under directory 'doc'
warning: no files found matching '*.html' under directory 'doc'
```

Downloading/unpacking feedparser (from -r requirements.txt (line 8))
  Running setup.py egg_info for package feedparser

Downloading/unpacking PyRSS2Gen (from -r requirements.txt (line 9))
  Running setup.py egg_info for package PyRSS2Gen

Downloading/unpacking BeautifulSoup (from -r requirements.txt (line 10))
  Running setup.py egg_info for package BeautifulSoup

Installing collected packages: psycopg2, django, django-openid-auth, python-openid, feedparser, PyRSS2Gen, BeautifulSoup
  Running setup.py install for psycopg2
    building 'psycopg2._psycopg' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION="2.5.3 (dt dec pq3 ext)" -DPSYCOPG_EXTENSIONS=1 -DPSYCOPG_NEW_BOOLEAN=1 -DHAVE_PQFREEMEM=1 -DPG_VERSION_HEX=0x09010D -DPSYCOPG_EXTENSIONS=1 -DPSYCOPG_NEW_BOOLEAN=1 -DHAVE_PQFREEMEM=1 -I/usr/include/python2.7 -I. -I/usr/include/postgresql -I/usr/include/postgresql/9.1/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-2.7/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    In file included from psycopg/psycopgmodule.c:27:0:
    ./psycopg/psycopg.h:30:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /var/www/fmsgame/.venv/bin/python -c "import setuptools;__file__='/var/www/fmsgame/.venv/build/psycopg2/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-MeIp0V-record/install-record.txt --install-headers /var/www/fmsgame/.venv/include/site/python2.7:
    running install

running build

running build_py

running build_ext

building 'psycopg2._psycopg' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION="2.5.3 (dt dec pq3 ext)" -DPSYCOPG_EXTENSIONS=1 -DPSYCOPG_NEW_BOOLEAN=1 -DHAVE_PQFREEMEM=1 -DPG_VERSION_HEX=0x09010D -DPSYCOPG_EXTENSIONS=1 -DPSYCOPG_NEW_BOOLEAN=1 -DHAVE_PQFREEMEM=1 -I/usr/include/python2.7 -I. -I/usr/include/postgresql -I/usr/include/postgresql/9.1/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-2.7/psycopg/psycopgmodule.o -Wdeclaration-after-statement

In file included from psycopg/psycopgmodule.c:27:0:

./psycopg/psycopg.h:30:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

---

Command /var/www/fmsgame/.venv/bin/python -c "import setuptools;**file**='/var/www/fmsgame/.venv/build/psycopg2/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-MeIp0V-record/install-record.txt --install-headers /var/www/fmsgame/.venv/include/site/python2.7 failed with error code 1 in /var/www/fmsgame/.venv/build/psycopg2
Storing complete log in /root/.pip/pip.log

**Comment by dracos** [comment]
Just to check, in case you missed it in the readme, this is an unfinished, unsupported project - I'm afraid you're pretty much on your own if you want to try and use this code! However, this error is straightforward - and somewhat explained in psycopg2's installation documentation at http://initd.org/psycopg/docs/install.html#install-from-source - you need to have python-dev and libpq-dev packages installed (or equivalent for your OS). Alternatively, you could install the system packaged psycopg2 (as given at http://initd.org/psycopg/docs/install.html#install-from-a-package ) and let the virtualenv use system packages by specifying `--system-site-packages` when you create the virtualenv.

**Comment by loran750** [comment]
hi

i didn't miss the fact that this is an unfinished project ;) anyway, i would like to test the gamification thing, that could be interesting. Juste for my information.

thanks, i will add this packages
